### PR TITLE
fixes TTS voice uninstall script

### LINKED ISSUE #9: `uninstall` throws error and doesn't complete task on macos 14.5
While testing #8, I saw that `uninstall` does not work on my machine. I have confirmed that it is installed and that `serve` works correctly. When I run `uninstall` I get this not entirely helpful error:

```
Uninstall text to speech extension and other support

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    '/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -f -R -trusted -u MacOSATDriverServer.app'
  ],
  cmd: '/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -f -R -trusted -u MacOSATDriverServer.app',
  stdout: '',
  stderr: ''
}
```

I am on macOS 14.5.

### PR DESCRIPTION
**Pull request by ChrisC**
Confirmed that this works on macos 15.4.1. TBD on how we'll want to handle support for older versions of macOS. 

possibly closes #9 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207339725618892

### CODE REVIEW

File: shared/install/macos.js [hunk 1]
```diff
@@ -161,7 +161,10 @@ const isInstalled = async function () {
  */
 const getExecOptions = async function () {
   return {
-    cwd: resolve(__dirname, '../../MacOSATDriverServer/Build/Debug'),
+    cwd: resolve(
+      __dirname,
+      '../../packages/macos-at-driver-server/MacOSATDriverServer/Build/Debug',
+    ),
```
Comment (jugglinmike) [inline shared/install/macos.js:167]: [The entire `shared` directory is copied into the package directory whenever we package the module for publication](https://github.com/bocoup/at-driver-servers/blob/e75a2e9952b79022984b5169fd05015df366a0ab/packages/macos-at-driver-server/package.json#L16), so the path as expressed on the `main` branch is actually correct. For local testing, you can run `npm run prepack` from the `packages/macos-at-driver-server` directory, and then use the `./shared/bin/at-driver` executable from there.

(Won't it be nice when we remove Windows support and get rid of this indirection?)

**Review by jugglinmike — APPROVED** [review]
I'm unable to verify this since I'm unable to install the voice locally on my current system. That said, if this patch only amounts fixing the issue for you alone, that's still an improvement over the status quo!
